// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJmFox8PWk_z8bGZUsIEyz4p7qzfkV6Ss',
    appId: '1:507884686856:web:360c27077148ff2f25cbbd',
    messagingSenderId: '507884686856',
    projectId: 'hello-flutter-001',
    authDomain: 'hello-flutter-001.firebaseapp.com',
    storageBucket: 'hello-flutter-001.appspot.com',
    measurementId: 'G-EE784K90RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALCFFJNCCZ3Tdra-xGPoZGGkxog61ah_c',
    appId: '1:507884686856:android:8e58092066edee7725cbbd',
    messagingSenderId: '507884686856',
    projectId: 'hello-flutter-001',
    storageBucket: 'hello-flutter-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6VfWSjciDPcC5Z6pO8B9H3bp5LH5r43Y',
    appId: '1:507884686856:ios:12e6193f4b23774525cbbd',
    messagingSenderId: '507884686856',
    projectId: 'hello-flutter-001',
    storageBucket: 'hello-flutter-001.appspot.com',
    iosClientId: '507884686856-j7psgbjnkhfrnuam61urhh6q516e41ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6VfWSjciDPcC5Z6pO8B9H3bp5LH5r43Y',
    appId: '1:507884686856:ios:014da3d8100311db25cbbd',
    messagingSenderId: '507884686856',
    projectId: 'hello-flutter-001',
    storageBucket: 'hello-flutter-001.appspot.com',
    iosClientId: '507884686856-4f85grq24bb72q3rqoeg63ujgah2e91h.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld.RunnerTests',
  );
}
